services:
  # A Docker web service
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: uv sync
    startCommand: uv run uvicorn main:app --host 0.0.0.0 --port $PORT
